apiVersion: v1
kind: Service
metadata:
  name: firstapp
  namespace: namespace-workflow-1719733579327
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: firstapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000